[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
js-sys = "0.3"
gloo = "0.8"
gloo-net = "0.2"
wasm-bindgen-futures = "0.4"

[dependencies.web-sys]
version = "0.3"
features = ["File", "Blob", "FormData", "DragEvent", "DataTransfer"]
